apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: test-k8s
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: app
          image: laravel-k8s-app:local
          ports:
            - containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z mysql 3306; do
                echo "Waiting for MySQL..."
                sleep 2
              done