apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: test-k8s
data:
  APP_ENV: production
  APP_DEBUG: "false"
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_DATABASE: app