apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: test-k8s
type: Opaque
stringData:
  DB_USERNAME: app
  DB_PASSWORD: secret
  APP_KEY: base64:D3/BgstHzykNziF4YXj6xit6c4nhu0SXw/Ykh/7bX+Q=